phira/locales/ru-RU/settings.ftl, phira/locales/ru-RU/song.ftl
settings.ftl edit with debug translation
=> Debug translation added

phira/locales/th-TH/song.ftl
=> Update song.ftl - Thai Review translation

phira/locales/fr-FR/chart_order.ftl, phira/locales/fr-FR/common.ftl, phira/locales/fr-FR/home.ftl, phira/locales/fr-FR/import.ftl, phira/locales/fr-FR/library.ftl, phira/locales/fr-FR/local.ftl, phira/locales/fr-FR/login.ftl, phira/locales/fr-FR/message.ftl, phira/locales/fr-FR/profile.ftl, phira/locales/fr-FR/rate.ftl, phira/locales/fr-FR/respack.ftl, phira/locales/fr-FR/settings.ftl, phira/locales/fr-FR/song.ftl, phira/locales/fr-FR/tags.ftl, prpr/locales/fr-FR/chart_info.ftl, prpr/locales/fr-FR/dialog.ftl, prpr/locales/fr-FR/ending.ftl, prpr/locales/fr-FR/game.ftl, prpr/locales/fr-FR/scene.ftl
C'est la traduction française pour Phira, toute gratuite.
=> add fr-FR translation

phira/locales/fr-FR/common.ftl, phira/locales/fr-FR/login.ftl, phira/locales/fr-FR/settings.ftl, phira/locales/fr-FR/song.ftl, phira/locales/fr-FR/tags.ftl
This contain sligth tweaks to the french tranlation, mainly fixing the Song.ftl file being badly translated cause the word "upload" was translated to "Télécharger" instead of "Envoyer"
=> Updates FR translation even more

phira/locales/ko-KR/library.ftl, phira/locales/ko-KR/login.ftl, phira/locales/ko-KR/rate.ftl, phira/locales/ko-KR/settings.ftl, phira/locales/ko-KR/song.ftl, phira/locales/ko-KR/tags.ftl, prpr/locales/ko-KR/dialog.ftl, prpr/locales/ko-KR/game.ftl
in KR case -> There were many words that were translated directly translated words. So I modified it a little bit.
I am very interested in this project.
I hope it goes well, Good luck
=> Better Korean translation

phira/src/login.rs, phira/src/page/library.rs, phira/src/scene/song.rs, phira/src/tags.rs, prpr/src/scene.rs, prpr/src/scene/game.rs, prpr/src/ui.rs
=> Ios password input

phira/locales/zh-TW/library.ftl, phira/locales/zh-TW/login.ftl
另有包括針對台灣常用語優化後的更新請求
本PR以 08d50b838c1afcffbb05fb704fe734abb0757e00 進行更新
- 登陸 -> 登錄
- 根據 88bf0a9ab3bd0dd319e7958da855f317f0a67bf5 刪除 "online" 翻譯
- 根據 08d50b838c1afcffbb05fb704fe734abb0757e00 增加 "must-login" 翻譯
=> Update zh-TW Translation and fix typo "登陸" -> "登錄"

phira/locales/zh-TW/multiplayer.ftl, phira/locales/zh-TW/settings.ftl
本PR已包含 #99 之修改
這裡列出了單純簡轉繁以外的翻譯:
- 连接 -> 連線
- 登录 -> 登入
- 鉴权 -> 身分驗證
- 断开 -> 中斷
- 还没有 -> 尚未
- 消息不能为空 -> 訊息內容不能為空
- 消息 -> 訊息
- 房间主 -> 房主
疑慮翻譯:
- 鉴权 -> 身分驗證/授權  見 #98
Notice: 當前仍使用"chat-send-failaed"，見 #97
**🔴本PR以 3f4e816a8128944ef7c48adb7ea59b7092d0d524 為依據，之後仍可能有所更動🔴**
=> [Beta]Multiplayer zh-TW

phira/locales/zh-TW/settings.ftl
> #100 中亦包含此commit，允許逐步merge成功，除非做了修改
很抱歉在#77沒有注意到此處
_這是一處小修改_
=> Update zh-TW Translation: "准度->準度"

phira/locales/pl-PL/common.ftl, phira/locales/pl-PL/library.ftl, phira/locales/pl-PL/settings.ftl, phira/locales/pl-PL/song.ftl
=> Poland translation update by Sumar

prpr/locales/th-TH/parser.ftl
=> Update parser.ftl in TH

prpr/locales/pl-PL/parser.ftl
=> Update parser.ftl in PL By Sumar

phira/locales/th-TH/multiplayer.ftl
=> Update multiplayer.ftl TH

phira/locales/ja-JP/common.ftl, phira/locales/ja-JP/home.ftl, phira/locales/ja-JP/import.ftl, phira/locales/ja-JP/library.ftl, phira/locales/ja-JP/local.ftl, phira/locales/ja-JP/login.ftl, phira/locales/ja-JP/profile.ftl, phira/locales/ja-JP/respack.ftl, phira/locales/ja-JP/settings.ftl, phira/locales/ja-JP/song.ftl
Fixed unnatural Japanese, and some incomplete translations.
=> Update Japanese Translation

phira/locales/zh-TW/song.ftl
本PR包括：更新 207c472 的繁體中文(zh-TW)翻譯
(本次無特殊翻譯，僅作簡繁轉換)
<sub>會不會有人調侃這次PR挺爽啊，3分鐘完事兒...</sub>
<sup>hẽʔ˧˨，所以我在湊字數，先祝大家新年快樂吖</sup>
=> Update zh-TW translation

phira/locales/vi-VN/cali.ftl, phira/locales/vi-VN/chart_order.ftl, phira/locales/vi-VN/common.ftl, phira/locales/vi-VN/event.ftl, phira/locales/vi-VN/import.ftl, phira/locales/vi-VN/library.ftl, phira/locales/vi-VN/login.ftl, phira/locales/vi-VN/message.ftl, phira/locales/vi-VN/multiplayer.ftl, phira/locales/vi-VN/profile.ftl, phira/locales/vi-VN/resource.ftl, phira/locales/vi-VN/settings.ftl, phira/locales/vi-VN/song.ftl, prpr/locales/vi-VN/chart_info.ftl, prpr/locales/vi-VN/ending.ftl, prpr/locales/vi-VN/parser.ftl
I want to fix a few spelling errors in my vi-VN translation, there are quite a few :)
=> vi-VN:  Spelling correction

phira/locales/th-TH/song.ftl
Just a bit of transportation update and fix
=> Update and fix translation error for thai

phira/locales/fr-FR/cali.ftl, phira/locales/fr-FR/chapter.ftl, phira/locales/fr-FR/collection.ftl, phira/locales/fr-FR/common.ftl, phira/locales/fr-FR/import.ftl, phira/locales/fr-FR/multiplayer.ftl, phira/locales/fr-FR/resource.ftl, phira/locales/fr-FR/respack.ftl, phira/locales/fr-FR/settings.ftl, phira/locales/fr-FR/song.ftl, phira/locales/fr-FR/tags.ftl
Fixed some issues with the french translation and updated it too
=> French Translation update

prpr/src/core/note.rs
=> fix(#85): multi-hint

phira/src/charts_view.rs, phira/src/page.rs, phira/src/scene/chapter.rs, phira/src/scene/song.rs
=> fix: chapter offset adjusting (#243)

phira/locales/zh-TW/home.ftl
- c666f17
- `note-try-login-again`
<sub>~~審核我的Github紀錄的前輩好，我沒有刻意要刷PR數量的意思，望周知~~</sub>
=> chore(L10n): Update zh-TW translation

prpr/src/core/note.rs, prpr/src/judge.rs
Trying to fix strange judging logic.
=> Judgement fix

phira/locales/en-US/common.ftl, phira/locales/zh-CN/common.ftl, phira/src/client.rs, phira/src/data.rs, phira/src/login.rs, phira/src/page/home.rs, phira/src/page/library.rs, phira/src/scene.rs, prpr/src/scene.rs
Please test before merge
May fix #387
=> Fix: problem caused by `strict`

prpr/src/core/shaders/noise.glsl
=> fix noise.glsl

prpr/src/core/tween.rs
=> Add text Tween

prpr/src/l10n.rs
修复了可能出现的无效语言tag导致的黑屏问题，具体为什么在（类）原生系统会出现无效语言tag原因不明。
=> fix: Black screen, fixes #391

prpr/src/core/line.rs, prpr/src/parse/rpe.rs
=> feat: support parent chain

prpr/src/parse/rpe.rs
This pr prevents phira from panicking when the loaded chart has bezier event on extended event layer.
=> fix: call add_bezier on extended event layer
